In [45]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import joblib
from matplotlib.colors import ListedColormap

In [46]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4     #small random weights
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"initial weights before training: \n{self.weights}")
        self.eta = eta
        self.epochs = epochs

    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
        
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y, ):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")

        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"Error: \n{self.error}")

            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"Updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print("##"*10)
            
    def predict(self, test_input):
        test_with_bias = np.c_[test_input, -np.ones((len(test_input), 1))]
        z = self._z_outcome(test_with_bias, self.weights)
        return self.activation_function(z)

    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\nTotal loss: {total_loss}")
        return total_loss

    def _create_dir_return_path(self, model_dir, filename):
        os.makedirs(model_dir, exist_ok=True)
        return os.path.join(model_dir, filename)
        
    def save(self, filename, model_dir=None):
        if model_dir is not None:
            model_path_file = self._create_dir_return_path(model_dir, filename)
            joblib.dump(self, model_file_path)
        else:
            model_path_file = self._create_dir_return_path("model", filename)
            joblib.dump(self, model_path_file)

    def load(self, filepath):
        return joblib.load(filepath)

In [47]:
def prepare_data(df, target_col="y"):
    X = df.drop("y", axis=1)
    y = df["y"]
    return X, y

In [48]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1],
}

df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [49]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_AND = Perceptron(eta=ETA, epochs=EPOCHS)
model_AND.fit(X, y)
_ = model_AND.total_loss()

initial weights before training: 
[-8.45280792e-05  1.22741076e-05  1.44426747e-04]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[ 0.09991547  0.10001227 -0.09985557]
####################
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[-8.45280792e-05  1.22741076e-05  2.00144427e-01]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch: 3/10: 
[0.09991547 0.10001227 0.10014443]
####################
--------------------
for epoch >> 3
--------------------
Pred

In [50]:
model_AND.save(filename="and.model")

In [51]:
reload_and_model = Perceptron().load(filepath="model/and.model")

In [59]:
reload_and_model.predict(test_input=[[1,1]])

array([1])

In [52]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1],
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [53]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_OR = Perceptron(eta=ETA, epochs=EPOCHS)
model_OR.fit(X, y)
_ = model_OR.total_loss()

initial weights before training: 
[-0.00013019  0.00014992  0.00017298]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[ 0.19986981  0.20014992 -0.29982702]
####################
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[ 0.19986981  0.20014992 -0.19982702]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 3/10: 
[ 0.19986981  0.20014992 -0.09982702]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after for

In [60]:
model_OR.save(filename="or.model")

In [61]:
reload_or_model = Perceptron().load(filepath="model/or.model")

In [66]:
reload_or_model.predict(test_input=[[5,2]])

array([1])

In [55]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0],
}

df_XOR = pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [56]:
X, y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_XOR = Perceptron(eta=ETA, epochs=EPOCHS)
model_XOR.fit(X, y)
_ = model_XOR.total_loss()

initial weights before training: 
[ 8.61600033e-05 -1.06239285e-04  8.62378375e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[ 0.10008616  0.09989376 -0.19991376]
####################
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[ 8.61600033e-05 -1.06239285e-04  8.62378375e-05]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights after epoch: 3/10: 
[ 0.10008616  0.09989376 -0.19991376]
####################
--------------------
for epoch >> 3
--------------------
P